apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: pokemon-api
  description: awesome
  annotations:
    github.com/project-slug: daaray/pokeapi
#   annotations:
#     example.com/service-discovery: artistweb
#     circleci.com/project-slug: github/example-org/artist-website
  tags:
    - python
#   links:
#     - url: https://admin.example-org.com
#       title: Admin Dashboard
#       icon: dashboard
spec:
  type: service
  lifecycle: production
  owner: devx
  system: api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: my-component-api
spec:
  type: grpc
  definition: >
    service HelloService {
      rpc SayHello (HelloRequest) returns (HelloResponse);
    }

    message HelloRequest {
      string greeting = 1;
    }

    message HelloResponse {
      string reply = 1;
    }